workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play # Opcional, solo si tienes llaves de firma
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          cd flutter
          flutter pub get
      - name: Build APK (Release)
        script: |
          cd flutter
          flutter build apk --release --no-pub
    artifacts:
      - flutter/build/app/outputs/flutter-apk/app-release.apk
